# Generated by Django 4.2.3 on 2023-09-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain_auth', '0003_alter_emailverification_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='code',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
