# Generated by Django 4.2.3 on 2023-07-06 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('target', models.CharField(max_length=255, null=True)),
                ('group', models.CharField(default='public', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('NEW_FOLLOWER', 'NEW_FOLLOWER'), ('NEW_OFFER', 'NEW_OFFER'), ('NEW_FEATURE', 'NEW_FEATURE'), ('OFFER_UPDATED', 'OFFER_UPDATED'), ('NEW_ORDER', 'NEW_ORDER'), ('NEW_PRODUCT', 'NEW_PRODUCT'), ('NEW_EVALUATION', 'NEW_EVALUATION'), ('MARKETING_OFFER', 'MARKETING_OFFER'), ('FAVORIS_ADD', 'FAVORIS_ADD')], default='NEW_FEATURE', max_length=25)),
                ('image', models.IntegerField(default=None)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
