#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

daphne marketplace.asgi:application -b 0.0.0.0 -p 8000
python manage.py makemigrations
python manage.py migrate
python manage.py runserver 0.0.0.0:8000
