# Generated by Django 4.2.3 on 2023-07-06 23:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Domain_category', '0001_initial'),
        ('Domain_brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('product_slug', models.SlugField(max_length=255)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M')], default='XXL', max_length=255)),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('for_rental', models.BooleanField(default=False)),
                ('rental_days', models.IntegerField(null=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_end', models.DateTimeField(null=True)),
                ('change', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('NEVER_USE', 'NEVER_USE'), ('VERY_GOOD', 'VERY_GOOD'), ('GOOD', 'GOOD')], default='NEVER_USE', max_length=25)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ManyToManyField(to='Domain_brand.brand')),
                ('endCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domain_category.endcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domain_category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='assets/uploads/products')),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Domain_product.product')),
            ],
        ),
    ]
