# Generated by Django 4.2.3 on 2023-07-06 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('password', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(null=True)),
                ('age', models.DateTimeField(null=True)),
                ('bio', models.TextField(max_length=500, null=True)),
                ('last_login_ip', models.GenericIPAddressField(null=True)),
                ('user_slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('total_sold', models.IntegerField(default=0)),
                ('total_cancel', models.IntegerField(default=0)),
                ('total_complete', models.IntegerField(default=0)),
                ('cancel_rate', models.FloatField(default='0')),
                ('delivery_rate', models.FloatField(default='0')),
                ('user_rate', models.FloatField(default='0')),
                ('lang', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('YE', 'Yemba'), ('GO', "Ghomala'a"), ('EWO', 'Ewondo'), ('FU', 'Fulfulde'), ('DU', 'Duala')], default='FR', max_length=50)),
                ('new_follower', models.BooleanField(default=True)),
                ('new_order', models.BooleanField(default=True)),
                ('new_offer', models.BooleanField(default=True)),
                ('new_favorite', models.BooleanField(default=True)),
                ('new_evaluation', models.BooleanField(default=True)),
                ('banned_level', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
