# Generated by Django 4.2.3 on 2023-07-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
