# Generated by Django 4.2.3 on 2023-07-07 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_alter_passwordreset_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 1, 51, 54, 735727, tzinfo=datetime.timezone.utc)),
        ),
    ]
