# Generated by Django 4.2.3 on 2023-09-11 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0003_alter_passwordreset_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 5, 12, 53, 757037, tzinfo=datetime.timezone.utc)),
        ),
    ]
