# Generated by Django 4.2.3 on 2023-07-06 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Domain_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('WAITING', 'WAITING'), ('ACCEPTED', 'ACCEPTED'), ('REFUSED', 'REFUSED'), ('EXPIRED', 'EXPIRED')], default='WAITING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2023, 7, 8, 23, 15, 5, 710957, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_offers', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domain_product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
