# Generated by Django 4.2.3 on 2023-07-07 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 0, 56, 57, 658007, tzinfo=datetime.timezone.utc)),
        ),
    ]
