# Generated by Django 4.2.3 on 2023-07-07 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offer_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 1, 21, 54, 750490, tzinfo=datetime.timezone.utc)),
        ),
    ]
