# Generated by Django 4.2.3 on 2023-07-06 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliverySetting', '0001_initial'),
        ('Domain_product', '0001_initial'),
        ('paiementMethod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('method_ref', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('fee', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('PURCHASE', 'Achat'), ('SALE', 'vente'), ('REFUND', 'remboursement')], default='PURCHASE', max_length=20)),
                ('method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='paiementMethod.paiementmethod')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Domain_product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('has_verification', models.BooleanField(default=False)),
                ('fee', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('seller_accept_order_expired_at', models.DateTimeField(default=datetime.datetime(2023, 7, 7, 23, 15, 5, 713795, tzinfo=datetime.timezone.utc))),
                ('client_confirm_ok_expired_at', models.DateTimeField(null=True)),
                ('order_expired_at', models.DateTimeField(default=datetime.datetime(2023, 7, 11, 23, 15, 5, 713820, tzinfo=datetime.timezone.utc))),
                ('client_confirm_receive_expired_at', models.DateTimeField(null=True)),
                ('seller_ship_to_deliver_expired_at', models.DateTimeField(null=True)),
                ('deliver_ship_expired_at', models.DateTimeField(null=True)),
                ('client_ok_time_expired_at', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('WAITING', 'en attente'), ('ACCEPTED', 'acceptée'), ('REFUSED', 'refusée'), ('CANCELED', 'annulée'), ('SUSPENDED', 'suspendu'), ('REFUNDED', 'remboursée'), ('FINISHED', 'terminée'), ('DELIVERING', 'en cours de livraison '), ('DELIVERED', 'livré'), ('VERIFIED', 'vérifié')], default='WAITING', max_length=25)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='deliverySetting.delivery')),
                ('method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='paiementMethod.paiementmethod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Domain_product.product')),
            ],
        ),
    ]
