# Generated by Django 4.2.3 on 2023-07-07 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 0, 56, 57, 662039, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_accept_order_expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 0, 56, 57, 661999, tzinfo=datetime.timezone.utc)),
        ),
    ]
