# Generated by Django 4.2.3 on 2023-07-07 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 1, 21, 54, 754679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_accept_order_expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 1, 21, 54, 754639, tzinfo=datetime.timezone.utc)),
        ),
    ]
