# Generated by Django 4.2.3 on 2023-09-11 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 4, 42, 53, 789867, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_accept_order_expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 4, 42, 53, 789848, tzinfo=datetime.timezone.utc)),
        ),
    ]
